{
 "title": "New dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tempo",
    "query": "15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests por segundo",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(observability_demo_request_seconds_count{uri=\"/user\"}[$tempo]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Sucesso / Erro",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(observability_demo_request_seconds_count{uri=\"/user\", status=~\"2..\"}[$tempo]))",
     "legendFormat": "sucesso"
    },
    {
     "expr": "sum(rate(observability_demo_request_seconds_count{uri=\"/user\", status!~\"2..\"}[$tempo]))",
     "legendFormat": "erro"
    }
   ]
  },
  {
   "title": "Requests por segundo - Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(observability_demo_request_seconds_count{uri=\"/user\"}[$tempo])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(observability_demo_request_seconds_bucket[$tempo])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(observability_demo_request_seconds_bucket[$tempo])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(observability_demo_request_seconds_bucket[5m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Total de Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(observability_demo_request_seconds_count{uri=\"/user\"}[$tempo]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total de Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(observability_demo_request_seconds_count{uri=\"/user\"})"
    }
   ]
  },
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Requests por segundo /user",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(observability_demo_request_seconds_count{uri=\"/account\"}[$tempo]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests por segundo - Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(observability_demo_request_seconds_count{uri=\"/account\"}[$tempo])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Sucesso / Erro",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(observability_demo_request_seconds_count{uri=\"/account\", status=~\"2..\"}[$tempo]))",
     "legendFormat": "sucesso"
    },
    {
     "expr": "sum(rate(observability_demo_request_seconds_count{uri=\"/account\", status!~\"2..\"}[$tempo]))",
     "legendFormat": "erro"
    }
   ]
  }
 ]
}